### ISSUE TITLE
custom formats support only string type

### ISSUE THREAD

**Issue by erezmarmor** [horejsek/python-fastjsonschema#100]
**fastjsonschema==2.14.4**
when using custom formats, the documentation doesn't explicitly state which types are supported:

> Also, you can pass mapping for custom formats. Key is the name of your formatter and value can be regular expression which will be compiled or callback returning bool (or you can raise your own exception).

therefore, I assumed all are and used a custom format for the integer type (see attached file for code).
![fastjsonschema_custom_formats_bug](https://user-images.githubusercontent.com/16885498/82427481-d902db80-9a91-11ea-80b7-b05816a4e279.png)

inspecting the generated validator code it's easy to see only string type is supported.

please allow custom formats to all types or update the documentation accordingly.

**Comment by horejsek** [comment]
Format can be callback, but format is used only for string. Try your example with string instead and it will work as expected.

https://json-schema.org/understanding-json-schema/reference/string.html#format

**Comment by erezmarmor** [comment]
yes, I realize it works only for string 

> inspecting the generated validator code it's easy to see only string type is supported.

now that I've read the [custom format specification](https://json-schema.org/understanding-json-schema/reference/string.html#format)  perhaps the documentation of fastjsonschema should reflect that more clearly

regardless, thanks for your reply
