### ISSUE TITLE
Possible to use set of related schema files?

### ISSUE THREAD

**Issue by llaisdy** [horejsek/python-fastjsonschema#102]
More a query (not covered in the docs afaics) than an issue: is it possible to use multiple related schema files to validate a json object? Specifically, with `$ref` fields on one schema pointing to `$id` fields in another, eg:

```
"start_ts": {
      "$ref": "common-schema.json#definitions/timestamp"
},
```

From a quick scan of the doc page and the issues/PRs it looks like I might need to import upstream definitions into the main schema file --- but I can still use `$ref` & `$id` within the one schema file ---, is that right?

Thanks

**Comment by horejsek** [comment]
You can use definition from other file schema, but you need to provide full URL. For example: `http://json-schema.org/draft-07/schema#definitions/nonNegativeInteger`.  See RFC for more info: http://json-schema.org/draft/2019-09/json-schema-core.html
