### ISSUE TITLE
Unexpected subobject validation / defaults behavior

### ISSUE THREAD

**Issue by mkorkalo** [horejsek/python-fastjsonschema#104]
I'm not sure if this is a bug or just "works as expected by JSON schema standard".
Reporting nevertheless.

My test script:
```
import fastjsonschema
import json


schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "test_subobject": {
            "default": {},
            "properties": {"a": {"type": "boolean", "default": True}},
            "type": "object",
        }
    },
    "type": "object",
}

cfg = {}
fastjsonschema.validate(schema, cfg)
print(json.dumps(cfg))

cfg = {"test_subobject": {}}
fastjsonschema.validate(schema, cfg)
print(json.dumps(cfg))
```

Running the script results in:
```
$ python3 test.py                                                                                                                                                                      15:43:06
{"test_subobject": {}}
{"test_subobject": {"a": true}}
```

Is this behavior to be expected?
Setting a default object in the schema results in subobject default value not being validated against itself.
However, giving validator a default object manually will result in validation and thus, default values being set.

**Comment by horejsek** [comment]
Default property is not precisely defined as it's not used by validators, but can be used by tools to provide default value. How to implement it is not defined. I chose to use it for this implementation as it's handy. The behaviour you observe is expected. For me, it's better this way as you can define your default for `test_subobject` with included `a: true` already, and you have option to have different default for case when `subobject` is missing completely and when only `a` is missing. E.g., you can specify that default of subobject can be `{"a": false}` and default for `a` can be `true`.

**Comment by mkorkalo** [comment]
Then how about this:
```
import fastjsonschema
import sys
import json


schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "test_subobject": {
            "default": {"a": 100},
            "properties": {"a": {"type": "boolean", "default": True}},
            "type": "object",
            "additionalProperties": False
        }
    },
    "type": "object",
}

cfg = {}
fastjsonschema.validate(schema, cfg)
print("Object generated using default validator")
print(json.dumps(cfg))
print("Re-validating against schema")
fastjsonschema.validate(schema, cfg)
print(json.dumps(cfg))
```

It's possible to create invalid objects through the validator using this, because in addition to not populating default values, the object is not checked for validity. I would expect an object coming through the JSON validator to be valid.
Yes, the schema is bad but that's an easy mistake to make.

Also, because of this behavior, you need to show default values twice in your schema (once in the schema, once in the default object). For my cases anyway the normal situation is this. Also, you could still give different default in the default object if you like, but you would not have to.

**Comment by horejsek** [comment]
From RFC (https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.2): `It is RECOMMENDED that a default value be valid against the associated schema.` I agree default value should be valid but it's not required, that's why it's not checked. It's up to author to decide what should be default value.
