### ISSUE TITLE
Incomplete support for draft7 boolean types

### ISSUE THREAD

**Issue by talwararjun4** [horejsek/python-fastjsonschema#105]
compile method fails to compile the schema definition which contains booleans even though they are supported by the draft7 specification.

Example schema on which the compile function throws an error:
```
{
"properties" : {
"value" : true
},
"required" : ["value"]
}

instance :

{"value" : "any value"}
```

This is how I'm trying to run the code:
```
import fastjsonschema
import json 
with open("schema_1.json") as schema_file:
    schema = json.load(schema_file)
    strformat = json.dumps(schema)

validate = fastjsonschema.compile(strformat) #this fails
```

**Comment by horejsek** [comment]
Hi. You need to pass Python object, not string. I.e.: `fastjsonschema.compile(schema)`.
