### ISSUE TITLE
Custom formats for non-string types

### ISSUE THREAD

**Issue by n2N8Z** [horejsek/python-fastjsonschema#108]
AWS publishes JSON Schema documents for its events that include custom formats for non-string types.

e.g. 
```
        "lastModifiedTime": {
          "format": "int64",
          "type": "integer"
        }

```

These custom formats generate parsing errors in fjs when not defined, but are not used when they are defined.

See full schema for S3 events attached.

[aws.s3@AWSAPICallViaCloudTrail-v2.JSONSchemaDraft4.txt](https://github.com/horejsek/python-fastjsonschema/files/5710617/aws.s3%40AWSAPICallViaCloudTrail-v2.JSONSchemaDraft4.txt)

**Comment by n2N8Z** [comment]
I see now this has been raised before #100 .
The link in the comments https://json-schema.org/understanding-json-schema/reference/string.html#format point out that format only applies to string types, which would make AWS's schema invalid.
But the link also mentions "A JSON Schema validator will ignore any format type that it does not understand.". So fjs should ignore "int64".

**Comment by horejsek** [comment]
Since 2.19.0 you can pass `use_formats=False` to disable custom formats.
