### ISSUE TITLE
Should exceptions thrown by custom format checkers be caught and re-thrown as JsonSchemaException?

### ISSUE THREAD

**Issue by gpakosz** [horejsek/python-fastjsonschema#123]
Title says it all,

When a custom format checker function throws instead of returning `false`, should it be caught and re-thrown as `JsonSchemaException`?

Alternatively, should there be a way for custom format checker functions to return a message alongside a `bool`?

**Comment by horejsek** [comment]
Well, I don't see a reason why. Custom format function should return True or False to indicate validity of the provided data. Any fail is up to the owner of the custom format function. If your checker can throw exception and you don't want them to leak, catch it inside the function to always return True or False. Or you can wrap it into JsonSchemaException yourself, even if its 3rd party checker by using decorator pattern. Or you just leave the original exception and the responsibility should be on the part of the code which calls the validation to expect such exception and handle it if needed. Wrapping it automatically would slow down the execution and could potentially hide issues in your code.
