### ISSUE TITLE
Exception data contains the word "data" in most instances

### ISSUE THREAD

**Issue by bb-rrogers** [horejsek/python-fastjsonschema#133]
Heya All,

Firstly, just want to say this is a great tool, I have been experimenting with it for a while now and does a great job.
I am opening up this issue to figure out why we have included the word data in most messages/values within the SchemaValidationError object.

When printing out the SchemaValidationError.path we get: ['data','userId']
When printing out the SchemaValidationError.name we get: data.userId
When printing out the SchemaValidationError.message we get: Failed schema validation. Error: data.userId must be shorter than or equal to 8 characters, Path: ['data', 'userId'], Data: werqwerqwerqwerqwerqwerq

I was hoping to be able to get something simple like this:
When printing out the SchemaValidationError.path we get: userId
When printing out the SchemaValidationError.name we get: userId
When printing out the SchemaValidationError.message we get: Failed schema validation. Error: userId must be shorter than or equal to 8 characters, Path: userId, Data: werqwerqwerqwerqwerqwerq

I am trying to understand the reasoning for the word 'data' and was curious if there is a way to strip it without manually parsing each property and removing that.

**Comment by horejsek** [comment]
Data represents the root. It is done this way to cover also instances when you want to have simple array, or just a number. So then you get "data must be a number", or "data[2] must be a string", and so on. The message is not meant to be used for users anyway. I encourage it to replace it with something more meaningful for users.

**Comment by dimaqq** [comment]
I can see two options:
* `message.replace("data.", "your_thing.", 1)` (easy)
* re-implement message for every `.rule` (and keep your messages in sync with this library)

The latter is probably **the way** if localisation is needed.
