### ISSUE TITLE
Provide tests in sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [horejsek/python-fastjsonschema#138]
Hi! I'm currently looking into packaging this project for Arch Linux.

We usually rely on upstream's unit tests to figure out whether a given project is compatible with our Python ecosystem.
Unfortunately the tests and test data is missing from the sdist tarballs on pypi.org. Would it be possible to add them?

As this project uses a git submodule for its test data, those files will also not be included in github's auto-generated release tarballs. So downstreams have to rely on git to get to the files and run tests, which is a bit suboptimal.

Thanks for the consideration!

**Comment by mtelka** [comment]
+1 for adding tests to sdist.  It would be helpful for OpenIndiana too.  Thank you!

**Comment by dvzrv** [comment]
@horejsek hi, could this please be considered? :)

**Comment by horejsek** [comment]
It will be part of the next release.
https://github.com/horejsek/python-fastjsonschema/commit/ddbf84e00a2761250e75016fb6a07a49bc589a03
