### ISSUE TITLE
Feature request: setting const values to default

### ISSUE THREAD

**Issue by theahura** [horejsek/python-fastjsonschema#147]
I know this isn't in the jsonschema spec, but I think it would be really user friendly to have a validator option that automatically sets the const value to the default value for a passed in schema. 

Right now, the following code will fail:
```python
import fastjsonschema

schema = {
    '$schema': 'http://json-schema.org/draft-07/schema#',
    '$id': '/foo',
    'type': 'object',
    'properties': {
        'name': {
            'const': 'helloworld'
        },
    },
    'required': ['name'],
}

validator = fastjsonschema.compile(schema, use_default=True)

print(validator({}))
```
because there is no passed in value for `name`. It would be great if this instead returned
```
{ 'name': 'helloworld' }
```
The fastjsonschema.compile step already has a `use_default` value (https://github.com/horejsek/python-fastjsonschema/blob/master/fastjsonschema/__init__.py#L119); perhaps that could take be an enum that also validates `const` as `default`, or maybe it should take in another boolean parameter like `use_const_as_default`?

**Comment by horejsek** [comment]
I think this is not very good idea. There is already option to pass default for your need and I don't see why there should be two ways of doing the same. You can define your schema as `prop: {const: foo, default: foo}`, for example.
