### ISSUE TITLE
ValueError: unknown url type when using $ref to another file

### ISSUE THREAD

**Issue by anton-petrov** [horejsek/python-fastjsonschema#150]
Hello, maybe this is not a bug, but my inability to use this library, but anyway...

How to properly use [python-fastjsonschema](https://github.com/horejsek/python-fastjsonschema) for validating such documents, for example:
```
"object": {
    "properties": {
        "objects": {
            "type": "array",
            "items": {
                "allOf": [
                    {
                        "$ref": "file_name.json#/definitions/base"
                    },
...
```
I'm using links to another schema files, but getting `ValueError: unknown url type` error for the $ref files, when trying to compile validation function:
```
with open(schema_filename) as schema_file:
    schema = load(schema_file)
    validator = fastjsonschema.compile(schema)
```

With [python-jsonschema](https://github.com/python-jsonschema/jsonschema) this piece of code works good:
```
with open(schema_filename) as schema_file:
      schema = load(schema_file)
      try:
          Draft7Validator.check_schema(schema)
      except SchemaError:
          print(f'Schema {schema_filename} is not a valid draft-07 json schema')
          return None
      resolver = RefResolver(base_uri=f'file:///.../schemas/', schema=schema)
      return Draft7Validator(schema, resolver=resolver)
```

So, the question is - how to use resolver or something other trick to allow the _fastjsonschema_ correctly resolve link names?

Thanks!

**Comment by jkorinth** [comment]
Got the same problem. How did you solve it, @anton-petrov ?
