### ISSUE TITLE
are the compiled validation functions cached?

### ISSUE THREAD

**Issue by renaud** [horejsek/python-fastjsonschema#158]
From the Python docs for [re.compile()](http://docs.python.org/library/re.html#re.compile):

    Note The compiled versions of the most recent patterns passed to re.match(), 
    re.search() or re.compile() are cached, so programs that use only a few regular 
    expressions at a time needn’t worry about compiling regular expressions.

Is there such a mechanism in fastjsonschema?

**Comment by horejsek** [comment]
No, it is not in place. But it could be an interesting feature. Maybe in future. :-)

**Comment by horejsek** [comment]
Actually, I was wrong. Of course regexps are compiled.
