### ISSUE TITLE
Wrong tag name for 2.17.0

### ISSUE THREAD

**Issue by dvzrv** [horejsek/python-fastjsonschema#172]
Hi! I package this project for Arch Linux and noticed that the tag name for 2.17.0 has an additional dot prepended (which I guess is not really a thing in semver): https://github.com/horejsek/python-fastjsonschema/releases/tag/v.2.17.0

As I am relying on the commit this tag points at, I guess I am fine, but just wanted to point this out in case you want to fix this (e.g. by creating a v2.17.0 on that same commit).

**Comment by horejsek** [comment]
Sorry for the issue, it's fixed now.
