### ISSUE TITLE
Feature request: make "context in exceptions" optional

### ISSUE THREAD

**Issue by vanschelven** [horejsek/python-fastjsonschema#187]
I'm using fjs to generate python code that does the validation (i.e. `compile_to_code`)

I'm working around #72 by just falling back to good (bad) old `jsonschema` and `best_guess` in the case I have a validationerror.

That means I don't use any of the information that's present in the `JsonSchemaValueException`. Looking at that code, I noticed that ~75% (out of a whopping 2.5MB) is used by the `definition` parts of the generated exceptions. When you have deeply nested definitions, that is to be expected, since the relevant part of the definition (for some part) is repeated throughout the tree.

Since I don't use that information, generating it (and loading it) seems wasteful. It would be nice if `compile_to_code` had a parameter that controlled the behavior of the generated `raise JsonSchemaValueException`, basically making (the relevant parts of) [this commit](93194b890f81e140c099654cd65b4f9e82a23e6d) conditional.

I managed to work around this a bit by hacking around in `def exc` but that doesn't "quite feel right".

**Comment by horejsek** [comment]
That is an exciting idea. I will measure how it changes the performance, and if it's improving it significantly, I will provide an option for that.

**Comment by horejsek** [comment]
A quick check shows it could reduce time by 50%! For cases when you expect mostly valid inputs and you don't care about details, it could speed up greatly the performance. Will provide this feature for sure. :-)

**Comment by horejsek** [comment]
Added `detailed_exceptions` parameter that is True by default and can be turned off in v2.21.0. It can be twice as fast.
