### ISSUE TITLE
Draft-07 support

### ISSUE THREAD

**Issue by Jokipii** [horejsek/python-fastjsonschema#19]
Here is experimental version that can support different versions of JSON Schema
https://github.com/Jokipii/python-fastjsonschema
All feedback is welcome.

# Current version test results against draft-07:

============= 467 passed, 47 xfailed, 40 xpassed in 5.66 seconds ==============

### Following tests fail (done means is already fixed)

Shared with draft-06:
- [x] const.json / const validation / another value is invalid
- [x] const.json / const validation / another type is invalid
- [x] const.json / const with object / another object is invalid
- [x] const.json / const with object / another type is invalid
- [x] const.json / const with array / another array item is invalid
- [x] const.json / const with array / array with additional items is invalid
- [x] const.json / const with null / not null is invalid
- [x] contains.json / contains keyword validation / array without items matching schema is invalid
- [x] contains.json / contains keyword validation / empty array is invalid
- [x] contains.json / contains keyword with const keyword / array without item 5 is invalid
- [x] contains.json / contains keyword with boolean schema true / empty array is invalid
- [x] contains.json / contains keyword with boolean schema false / any non-empty array is invalid
- [x] contains.json / contains keyword with boolean schema false / empty array is invalid
- [x] dependencies.json / dependencies with empty array / empty object
- [x] dependencies.json / dependencies with empty array / object with one property
- [x] dependencies.json / dependencies with boolean subschemas / object with property having schema true is valid
- [x] dependencies.json / dependencies with boolean subschemas / object with property having schema false is invalid
- [x] dependencies.json / dependencies with boolean subschemas / object with both properties is invalid
- [x] dependencies.json / dependencies with boolean subschemas / empty object is valid
- [x] items.json / items with boolean schemas / array with one item is valid
- [x] items.json / items with boolean schemas / array with two items is invalid
- [x] items.json / items with boolean schemas / empty array is valid
- [x] ecmascript-regex.json / ECMA 262 regex non-compliance / ECMA 262 has no support for \\Z anchor from .NET
- [x] zeroTerminatedFloats.json / some languages do not distinguish between different types of numeric value / a float without fractional part is an integer
- [x] properties.json / properties with boolean schema / no property present is valid
- [x] properties.json / properties with boolean schema / only 'true' property present is valid
- [x] properties.json / properties with boolean schema / only 'false' property present is invalid
- [x] properties.json / properties with boolean schema / both properties present is invalid

Draft-07 specifics:
- [x] definitions.json / valid definition / valid definition schema
- [x] definitions.json / invalid definition / invalid definition schema
- [x] if-then-else.json / if and then without else / invalid through then
- [x] if-then-else.json / if and else without then / invalid through else
- [x] if-then-else.json / validate against correct branch, then vs else / invalid through then
- [x] if-then-else.json / validate against correct branch, then vs else / invalid through else
- [x] content.json / validation of string-encoded content based on media type / an invalid JSON document
- [x] content.json / validation of binary string-encoding / an invalid base64 string (% is not a valid character)
- [x] content.json / validation of binary-encoded media type documents / a validly-encoded invalid JSON document
- [x] content.json / validation of binary-encoded media type documents / an invalid base64 string that is valid JSON
- [x] iri.json / validation of IRIs / a valid IRI based on IPv6
- [x] relative-json-pointer.json / validation of Relative JSON Pointers (RJP) / a valid upwards RJP
- [x] relative-json-pointer.json / validation of Relative JSON Pointers (RJP) / a valid downwards RJP
- [x] relative-json-pointer.json / validation of Relative JSON Pointers (RJP) / a valid up and then down RJP, with array index
- [x] relative-json-pointer.json / validation of Relative JSON Pointers (RJP) / a valid RJP taking the member or index name
- [x] time.json / validation of time strings / an invalid time string
- [x] time.json / validation of time strings / only RFC3339 not all of ISO 8601 are valid
- [x] ref.json / remote ref, containing refs itself / remote ref valid
- [x] ref.json / remote ref, containing refs itself / remote ref invalid

**Comment by Jokipii** [comment]
Passes 100% of the official JSON Schema Test Suite

**Comment by horejsek** [comment]
I chose different path and did some performance optimisations. Now I want to focus on some small refactor and improving documentation. But almost all functionality is backported, only few tests are still not passing.
