### ISSUE TITLE
'example.de' (and many others hostnames) not valid with hostname format 

### ISSUE THREAD

**Issue by FrederikP** [horejsek/python-fastjsonschema#26]
Aaand another one. Hope you aren't getting annoyed. Running this example throws a JsonSchemaException:

```
import fastjsonschema

schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://example.com/example.schema.json",
    "title": "Example",
    "description": "An example schema",
    "type": "object",
    "properties": {
        "host": {
            "type": "string",
            "description": "Some hostname",
            "format": "hostname"
        }   
    }
}

validate = fastjsonschema.compile(schema)

validate({"host": "example.de"})
```

For 'google.com' it works fine. I'll create a PR soon, probably.

**Comment by FrederikP** [comment]
This is the current regex:

```
^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{1,62}[A-Za-z0-9])$
```

As far as I see it, this means, the last part **always** has to be at least 3 chars long. This is a huge problem, as there are many tlds with 2 chars. (.de, .fr, etc.)

In the PR I'll probably use a different regex. But: As I said in the other issue today: I don't think regexes are a good solution for formats that can easily be validated using python standard library means (other than `re`).

**Comment by horejsek** [comment]
I agree, some formats would be better to validate by some extra library than by regexps. Also, some regexps are are not super correct for some cases. But it brings dependencies which I want to avoid until it's not really necessary. :-)

But maybe, if license allows it, I could copy-paste some code into this library to keep an eye on performance and avoid problems with changing dependencies. Will put on my todo list to check possibilities.

**Comment by FrederikP** [comment]
@horejsek Thanks for merging! I would be very happy if you can do a bugfix release with this in the near future, because this issue keeps us from rolling out a component that we switched from jsonschema to your library (because of draft7 support, performance and I like it better :) )

**Comment by horejsek** [comment]
Done, v2.3 :-)

**Comment by horejsek** [comment]
Glad it helped your component! :-)
