### ISSUE TITLE
Feature Request: Make unified ip_address format

### ISSUE THREAD

**Issue by RobertKirk** [horejsek/python-fastjsonschema#41]
I'm happy to do this myself if it's something you would be interested in having, but it would mean having a format `ip` (or maybe `ip_address`) which is just either `ipv4` or `ipv6`. Then we could write:

`"remote_addr": {"type": "string", "format": "ip"}`

rather than

`"remote_addr": {"type": "string", "oneOf": ["format": "ipv4", "format": "ipv6"]}`

**Comment by horejsek** [comment]
Yeah, that would be good. But this format is not part of JSON specification if I see it correctly, so not sure if it's good idea to implement it. Maybe I could do it with some parameter which will turn the add-on (and maybe also another one one day as well) on.

**Comment by horejsek** [comment]
This will be possible to do after the following merge request will be merged: https://github.com/horejsek/python-fastjsonschema/pull/57

**Comment by RobertKirk** [comment]
Excellent, thanks. How long will there be until you release a new version after that's merged?

**Comment by horejsek** [comment]
It's merged, but needs work to fix it. Estimation is next week.

**Comment by horejsek** [comment]
I did a work on it this evening. It's in a master. I want to include more stuff, release next week. Expected version 2.14.

**Comment by RobertKirk** [comment]
Thanks a lot.
