### ISSUE TITLE
remove requests for smaller memory usage

### ISSUE THREAD

**Issue by remorses** [horejsek/python-fastjsonschema#43]
I like the fact that this library is very fast compared to json schema, but in term of memory usage this lib isn't any better.
The problem Is that `requests` takes about 15 Mb of memory after being loaded and the result is that the module is 20 Mb big.
Maybe I will find time to replace `requests` with `urllib`, are you ok with a pull request like that?
memory_profiler result:
```markdown
Line #    Mem usage    Increment   Line Contents
================================================
     6     24.7 MiB     24.7 MiB       @profile
     7                                 def main():
     8
     9     40.5 MiB     15.8 MiB           import fastjsonschema
```
The lib would takes 0.1 Mb of memory without requests and about 6 Mb using urllib
```markdown
Line #    Mem usage    Increment   Line Contents
================================================
     6     24.7 MiB     24.7 MiB       @profile
     7                                 def main():
     8
     9     40.4 MiB     15.7 MiB           import requests

    10     40.5 MiB      0.1 MiB           import fastjsonschema
```

**Comment by horejsek** [comment]
That's interesting. Yes, I would allow it. There is only one call in ref_resolve, so it should be quite easy. Maybe would be good to write the test to check memory usage so in the future it will stay reasonable as well. :-)

**Comment by remorses** [comment]
Made pull request #44.
