### ISSUE TITLE
Question: Custom types

### ISSUE THREAD

**Issue by earonesty** [horejsek/python-fastjsonschema#48]
I have a schema which requires a datatype "string".   I'd like to change this to require a datatype "safestring" (a non-folded, memory clearing version of string) which cannot be derived from str.

Is there a fairly trivial way to either:

a) change the type to reference a sutom class or
b) change fjs conception of what is allowable for strings

For now I just monkey patch in my own CodeGeneratorDraft07 class and modify the JSON_TYPE_TO_PYTHON_TYPE instance.

If not, I'd be happy to add it

**Comment by horejsek** [comment]
The way, you can add your own functionality of this type, is to inherit generator class and override `generate_type` method. See https://github.com/horejsek/python-fastjsonschema/blob/master/fastjsonschema/draft04.py#L65

Your solution could be something like:

```python
class MyCodeGenerator(CodeGeneratorDraft07):
    def generate_type(self):
        if self._definition['type'] == 'mytype':
            # ...
        super().generate_type()
```

I don't feel good about adding dependency on Django's safestring into this library.
