### ISSUE TITLE
RFC 3339 Compliance

### ISSUE THREAD

**Issue by kjmph** [horejsek/python-fastjsonschema#51]
As seen in the JSON Schema Test Suite, only RFC 3339 compliant strings should be accepted for date-time. This means a time zone offset is required. As ISO 8601 specifies local time is applied when there is no time zone offset, there is ambiguity when client and servers are distributed across time zones.

Can we apply a new test in `test_format.py`?

```
    ('2018-02-05T14:17:10.00', exc),
```

And change date-time regexp in `fastjsonschema/draft04.py` to:

```
'date-time': r'^\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d(?:\.\d+)?(?:[+-][0-2]\d:[0-5]\d|Z)+\Z',
```

To highlight the change in the regexp, the trailing `?` is changed to a `+`.

**Comment by kjmph** [comment]
Here is a link to the test in the Test Suite:

https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/71843cbbd4be3194ee83253b402656550c8c0522/tests/draft7/optional/format/date-time.json#L17-L19

**Comment by kjmph** [comment]
Would you prefer me opening a Pull Request?

**Comment by horejsek** [comment]
There is no need to write a test. We can update test suit cases. I see there are a lot of new tests and around 40 of them found some bugs. I will fix it.

**Comment by horejsek** [comment]
I updated to latest JSON test suites and improved the code to pass the tests.

**Comment by kjmph** [comment]
Thank you very much for fixing all of that. Sorry to be a bother about it, yet the commits still didn't fix the RFC 3339 compliance issue that I raised. (Good catch on the others though).

For instance:

```
>>> import strict_rfc3339
>>> print(strict_rfc3339.validate_rfc3339("2018-02-05T14:17:10.00"))
False
>>> 
```

As you can see, the time zone offset is not optional. Can we change the `?` to a `+` for the time zone offset?

**Comment by horejsek** [comment]
Yeah, you are right, that didn't fix your report. The correct regexp is not `+` but _nothing_. See https://github.com/horejsek/python-fastjsonschema/commit/b1ba8065272353c171d5374f2ee6e1b7c63a68b2 for more details. Is that ok for you?

**Comment by kjmph** [comment]
Thank you!
