### ISSUE TITLE
Compiling incorrect schemas

### ISSUE THREAD

**Issue by alessio-b-zak** [horejsek/python-fastjsonschema#58]
Hi there!

I am trying to use this library for schema validation but I am finding that it compiles schemas that don't adhere to the standard for JSON schemas. 

For example, the following code:

```
fastjsonschema.compile({"title" : "test", "type": "object", "properties": {"test": ["THING"]}})
```

compiles with the latest version of fastjsonschema on Pypi however it is not a valid JSON schema. Does this library check to see if schemas are valid before compiling them?

**Comment by horejsek** [comment]
Hi. Can you share what is not valid in provided JSON schema? If JSON schema is not valid (by the library), exception is raised.

**Comment by alesfranek** [comment]
https://json-schema.org/understanding-json-schema/reference/object.html#properties

Values of the `properties` object must be JSON schemas. `["THING"]` is not a valid schema.

**Comment by horejsek** [comment]
Done in master, will be release next week.
