### ISSUE TITLE
Keep the variable name and path through references

### ISSUE THREAD

**Issue by horejsek** [horejsek/python-fastjsonschema#63]
> for me the most important feature is to keep track of the context/scope of where the validation process is at when the exception is thrown. so given: a schema:

article.json
```{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "additionalProperties": false,
  "properties": {
    "teaser" : { "$ref": "intro.json" },
    "prolog" : { "$ref": "intro.json" }
  }
}
```
when the error occurs during the prolog validation, the exception contains an attribute with value `article.prolog.....`  about where it happened (like the jsonschema library does).

_Originally posted by @isomogyi in https://github.com/horejsek/python-fastjsonschema/pull/61_

**Comment by machina-widmo** [comment]
Hello!

I'm a git noobie, but I had this same problem too. I actually ended up implementing this and it works through references.

The Ref Resolver will pull down the necessary references, and then inline the function definitions anyway. I basically passed around a list of "scope parts" and used context managers to add and remove parts from the list. That list was then passed to each of the generated validation functions.

I also had a fix where nested "try" statements could be optimized away leaving you with bad indentation. I found this by nesting "if" statements inside "oneOf" statements.

I'd love to submit pull requests for both.

**Comment by ZbigniewRA** [comment]
Hi @machina-widmo I would be very interested in your changes.
To submit a pull request you need to fork this repository, push your changes to your fork, and then create a pull request from your fork to the original repository.
You can see a video tutorial here: https://www.youtube.com/watch?v=OHV64qh-uyY

**Comment by ZbigniewRA** [comment]
I have created my own pull request for this issue: https://github.com/horejsek/python-fastjsonschema/pull/92
