### ISSUE TITLE
Special characters are not escaped in generated code

### ISSUE THREAD

**Issue by catb0t** [horejsek/python-fastjsonschema#69]
The following schema is valid, and works in a compliant draft 07 implementation 

```json 
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "x",
  "definitions": {
    "(+[{*#$%^&~`';:,.<> \"?!\\n}])": {
      "definitions": {
        "array": { "type": "array" },
        "object": { "type": "object" }
      },
      "anyOf": [
        { "$ref": "#/definitions/(+[{*#$%^&~`';:,.<> \"?!\\n}])/definitions/array" },
        { "$ref": "#/definitions/(+[{*#$%^&~`';:,.<> \"?!\\n}])/definitions/object" }
      ]
    }
  },
  "properties": {
    "x": { "$ref": "#/definitions/(+[{*#$%^&~`';:,.<> \"?!\\n}])" }
  }
}
```

```python3
import fastjsonschema, json
x = fastjsonschema.compile(json.load(open("./nested.schema.json", "r")))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.7/site-packages/fastjsonschema/__init__.py", line 103, in validate
    return compile(definition, handlers, formats)(data)
  File "/lib/python3.7/site-packages/fastjsonschema/__init__.py", line 167, in compile
    exec(code_generator.func_code, global_state)
  File "<string>", line 10
    validate_x__definitions_(+[{*_$_^&~`';_,_<> ?!\n}])(data__x)
```

Some characters are properly removed, including the `\"` and `#`, but many are not allowed in a Python name. 

Simply replacing them with `_` is not such a good solution because then a property named `#` is the same as `%` and `_` etc.

Using things like `_open_paren` to escape `(` etc, is somewhat ok, until a user makes a property named `_open_paren`, and then the names `(` and `_open_paren` are wrongly considered the same. 

A solution I have seen before (in [Brat](https://github.com/presidentbeef/brat/) code gen) is to give all special characters unique names, and then to make user-inputted names like identifiers surrounded by `__` 2 underscores, which are translated into `_dunder_` (for double-underscore), and then ensure that user input is expanded in a way that can never overlap with a different input.  

I cannot find where in the JSON Schema specification it says that any character other than `/` is allowed as an identifier / key name, but I am sure they are. NUL bytes are also [allowed](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-4.1) except I don't know of any Python JSON parsers that handle them properly, so I don't really care.

Also, double-escaping the characters doesn't help (one backslash alone is invalid to the JSON parser):
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "x",
  "definitions": {
    "\\(p\\)": {}
  },
  "properties": {
    "x": { "$ref": "#/definitions/\\(p\\)" }
  }
}
```

```python3
x = fastjsonschema.compile(json.load(open("./nested.schema.json", "r")))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cat/Sync/projects/git/pyrat/.venv/lib/python3.7/site-packages/fastjsonschema/__init__.py", line 167, in compile
    exec(code_generator.func_code, global_state)
  File "<string>", line 10
    validate_x__definitions_\(p\)(data__x)
                                         ^
SyntaxError: unexpected character after line continuation character
```

**Comment by catb0t** [comment]
My real use cases are schema keys like `let*` and `(gensym)`. The latter can be `__gensym` for now, that's OK, but `*` is important.

**Comment by horejsek** [comment]
Thanks for the report. I have an idea how to solve it--by making hash of the original name.

**Comment by catb0t** [comment]
I was wondering if you thought that method would be slow. Perhaps the hash lookup could be used only for names containing special characters that absolutely need it, to avoid slowing down most code?

**Comment by horejsek** [comment]
True, I forgot the hashes would have to be done during validation as well, not only during generating the code. 🤦‍♂ Yeah, doing it only for problematic variables would make sense. I will try think if there is other option without slowing down the validation process.

**Comment by horejsek** [comment]
For now I fixed it with simple removing of invalid characters in v2.14.2 which is also used for long time for property names. Let me know if this is not enough for now.
