### ISSUE TITLE
Unable to specify `"additionalProperties": true` in draft 4

### ISSUE THREAD

**Issue by wcloete** [horejsek/python-fastjsonschema#70]
The code snippet below fails with `fastjsonschema.exceptions.JsonSchemaDefinitionException: definition must be an object` while generating validation for `additionalProperties`.

```
import fastjsonschema
v = fastjsonschema.compile({
    '$schema': 'http://json-schema.org/draft-04/schema#',
    'required': ['id'],
    'type': 'object',
    'additionalProperties': True,
    'properties': {
        'id': {'type': 'string'}
    }
})
```

As I understand the [draft specification](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-12) a boolean is allowed.

**Comment by horejsek** [comment]
Yeah, this is a bug. By default it's true, so workaround is to not specify `additionalProperties`. When you want to disable any additional property, it's working ok.

**Comment by horejsek** [comment]
Will be fixed in next release.
