### ISSUE TITLE
How to compile with RefResolver?

### ISSUE THREAD

**Issue by damejovanoski** [horejsek/python-fastjsonschema#75]
Is it even possible?

**Comment by damejovanoski** [comment]
Also when added the reference the validation doesn't invalidate fields on the ref. level, but on the top level. I have added a test for that and it shows **data.timestamp must be bigger than or equal to 0** instead of **data.{FIELD_NAME}.timestamp must be bigger than or equal to 0**

**Comment by horejsek** [comment]
You created your own RefResolver and want to use it? Nope, this is not supported.

About your second comment, I think it's duplicate with https://github.com/horejsek/python-fastjsonschema/issues/63.
