### ISSUE TITLE
multipleOf does not work well when parameter is float

### ISSUE THREAD

**Issue by leiserfg** [horejsek/python-fastjsonschema#79]
Some schemas make use of multipleOf for limiting the numbre of decimal valid for a value, like  multipleOf `0.01` for currency.  But the check used by this lib usually fails:
```py
19.01/0.01 
>>>   1901.0000000000002
```
The easier way to fix it is by using `Decimal` if you are fine with my solution I can make a pr.

**Comment by horejsek** [comment]
Yep, sure, good idea. Go for it. :+1:
