### ISSUE TITLE
Support for validating tuples as arrays?

### ISSUE THREAD

**Issue by vEpiphyte** [horejsek/python-fastjsonschema#87]
Would a PR be accepted that modified fastjsonschema to validate a `tuple` object as an array?  Possible as an optional behavior?

The array validation function here https://github.com/horejsek/python-fastjsonschema/blob/master/fastjsonschema/generator.py#L275 only accepts a list, and I have a situation where I have data structures coming in from httpapi endpoints and custom RPC endpoints; and the RPC endpoints have all their array objects deserialized as tuples; so currently i'm having to wrap the fastjsonschema callable objects with a function that will recursively list-ify all values I pass in for validation.

This is similar to https://github.com/Julian/jsonschema/issues/148

**Comment by horejsek** [comment]
I guess this change will not brake anything, so I'm ok with it. Can you do it and write a test for it as well?

**Comment by vEpiphyte** [comment]
I can provide a PR and tests for it.  How quick can a release be made once that lands?

**Comment by vEpiphyte** [comment]
@horejsek I've opened a PR for this.

**Comment by horejsek** [comment]
Released 2.14.3 ;-)
