### ISSUE TITLE
Possibly update "id" in ref_resolver, to "$id"?

### ISSUE THREAD

**Issue by din14970** [horejsek/python-fastjsonschema#90]
I was getting some errors when validating against some of my schemas that make heavy use of internal and external references. I noticed that in the function `walk` in `ref_resolver.py` it searches for occurrences of `id`. When I read the JSON schema specification v7, `$ref` should look for `$id`, but in v4 this was indeed `id`. Perhaps some way could be implemented to support both?

**Comment by horejsek** [comment]
Fixed, will be released with next version.
