### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by Moguri** [horejsek/python-fastjsonschema#91]
Please upload wheel packages for this library. [This](https://pythonwheels.com/) goes into why wheels are useful. In the case of this package, I think the only thing that has to be done is to add `bdist_wheel` after `sdist` in the `upload` target in the Makefile. Virtual environments already install the `wheel` package by default, so the `venv` target should handle that requirement for building wheels.

I would upload a PR, but I cannot test the `upload` target without uploading something to PyPI. I did run `python setup.py bdist_wheel` and the wheel built just fine. It also installed fine in my test environment.

**Comment by horejsek** [comment]
Thanks, will do.

**Comment by horejsek** [comment]
Done with new release 2.14.4.

**Comment by Moguri** [comment]
Thanks!
