### ISSUE TITLE
Allow for validating Mappings and Sequences as objects and arrays.

### ISSUE THREAD

**Issue by ZbigniewRA** [horejsek/python-fastjsonschema#93]
Currently only `dicts` validate as `objects`, and `lists` and `tuples` as `arrays`.
For my own purposes I needed to generalize this, to make any `Mapping` validate as `object`, and any `Sequence` (except `str`) to validate as `array`.
I could create a pull request for it, it this feature will be deemed desirable.

**Comment by horejsek** [comment]
I'm afraid it would change significantly speed of the type check:

```
>>> timeit.timeit("isinstance({}, collections.abc.Mapping)", setup="import collections.abc")
0.4978000489999914
>>> timeit.timeit("isinstance({}, dict)")
0.14011686400000656

>>> timeit.timeit("isinstance([], collections.abc.Sequence)", setup="import collections.abc")
0.4966067460000261
>>> timeit.timeit("isinstance([], list)")
0.11277063199997883
```

If you want to have fast JSON validation, use simple types. If you want to keep your objects, you have two options: first is to inherit from dict or list and second is to do some conversion before passing data to this library.
